#+title: emacs.el
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el


* Essentials

This section configures the essentials of emacs, which are options that are not mode-specific

** package repositories and use-package

Load 'package, add prominent repositories, and update package data
#+begin_src emacs-lisp
  (require 'package)
  (setq package-archives '(("elpa" . "https://elpa.gnu.org/packages/")
                           ("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")))
  (package-initialize)
  (unless package-archive-contents (package-refresh-contents))
#+end_src

Install 'use-package if necessary, load it, and set it to auto-install packages hereon
#+begin_src emacs-lisp
  (unless (package-installed-p 'use-package) (package-install 'use-package))
  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

** no-littering (loading early required)

Load no-littering, move auto-save files from current to a dedicated folder,
and make sure that those files are ignored by recentf.
#+begin_src emacs-lisp
  (use-package no-littering)
  (setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
#+end_src
Known "bugs" if not loaded early:
- if loaded after (recentf-mode), causes recentf-open-files on startup-screen to be empty

** visual basics (no external packages required)

Maximize frames by default
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

Empty startup screen and scratch buffer
#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
  (setq initial-scratch-message nil)
#+end_src

Remove top menu bar, right scroll bar, and top tool bar.
#+begin_src emacs-lisp
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

Always start column mode.
#+begin_src emacs-lisp
  (setq column-number-mode t)
#+end_src

Display recently opened files on startup in GUI
#+begin_src emacs-lisp
  (if (display-graphic-p)
      (setq initial-buffer-choice 'recentf-open-files))
#+end_src

** behaviour basics (no external packages required)

Remember recently opened files, recent lines and minibuffer-history.
Limit size of history and ignore files generated by no-littering.
#+begin_src emacs-lisp
  (recentf-mode)
  (add-to-list 'recentf-exclude no-littering-var-directory)
  (add-to-list 'recentf-exclude no-littering-etc-directory)
  (setq history-length 64)
  (save-place-mode)
  (savehist-mode)
#+end_src

Auto-delete trailing whitespaces before save.
#+begin_src emacs-lisp
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+end_src

Auto-refresh files and dired buffers
#+begin_src emacs-lisp
  (global-auto-revert-mode)
  (setq global-auto-revert-non-file-buffers t)
#+end_src

Set default tab width to 2 (can be overwritten by other modes like julia-mode)
and indent using spaces instead of tabs
#+begin_src emacs-lisp
  (setq-default tab-width 2
                indent-tabs-mode nil)
#+end_src

Use C-x <arrow> to change between buffers
#+begin_src emacs-lisp
  (global-set-key (kbd "C-x <up>") 'windmove-up)
  (global-set-key (kbd "C-x <down>") 'windmove-down)
  (global-set-key (kbd "C-x <left>") 'windmove-left)
  (global-set-key (kbd "C-x <right>") 'windmove-right)
#+end_src

Make C-del, C-backspace, etc not put deleted text in kill-ring
#+begin_src emacs-lisp
  ;; Make ctrl+del etc not put deleted text in kill-ring
  ;; (so that clipboard remains unchanged)
  (defun my-delete-word (arg)
    "Delete characters forward until encountering the end of a word.
  With argument, do this that many times.
  This command does not push text to `kill-ring'."
    (interactive "p")
    (delete-region
     (point)
     (progn
       (forward-word arg)
       (point))))

  (defun my-backward-delete-word (arg)
    "Delete characters backward until encountering the beginning of a word.
  With argument, do this that many times.
  This command does not push text to `kill-ring'."
    (interactive "p")
    (my-delete-word (- arg)))

  (defun my-delete-line ()
    "Delete text from current position to end of line char.
  This command does not push text to `kill-ring'."
    (interactive)
    (delete-region
     (point)
     (progn (end-of-line 1) (point)))
    (delete-char 1))

  (defun my-delete-line-backward ()
    "Delete text between the beginning of the line to the cursor position.
  This command does not push text to `kill-ring'."
    (interactive)
    (let (p1 p2)
      (setq p1 (point))
      (beginning-of-line 1)
      (setq p2 (point))
      (delete-region p1 p2)))
                                          ; bind them to emacs's default shortcut keys:
  (global-set-key (kbd "C-S-k") 'my-delete-line-backward) ; Ctrl+Shift+k
  (global-set-key (kbd "C-k") 'my-delete-line)
  (global-set-key (kbd "M-d") 'my-delete-word)
  (global-set-key (kbd "<C-delete>") 'my-delete-word)
  (global-set-key (kbd "<C-backspace>") 'my-backward-delete-word)
  (global-set-key (kbd "<M-backspace>") 'my-backward-delete-word)
#+end_src

Dired list human readable sizes
#+begin_src emacs-lisp
  (setq dired-listing-switches "-alFh")
#+end_src

Overwrite selected text with typed text
#+begin_src emacs-lisp
  (delete-selection-mode 1)
#+end_src

** visual theme

Load dracula-theme in GUI, manoj-dark in terminal
#+begin_src emacs-lisp
  (use-package dracula-theme)
  (if (display-graphic-p)
      (load-theme 'dracula t)
    (load-theme 'manoj-dark t))
#+end_src

** visual fonts

Todo(?): fonts
#+begin_src emacs-lisp
#+end_src

** vertico

Load vertico for vertical minibuffer completion UI
#+begin_src emacs-lisp
  (use-package vertico
    :init
    (vertico-mode)

    ;; Different scroll margin
    ;; (setq vertico-scroll-margin 0)

    ;; Show more/less candidates
    (setq vertico-count 3)

    ;; Grow and shrink the Vertico minibuffer
    ;; (setq vertico-resize t)

    ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
    ;; (setq vertico-cycle t)
    )

  ;; Persist history over Emacs restarts. Vertico sorts by history position.
  (use-package savehist
    :init
    (savehist-mode))

  ;; A few more useful configurations...
  (use-package emacs
    :init
    ;; Add prompt indicator to `completing-read-multiple'.
    ;; We display [CRM<separator>], e.g., [CRM,] if the separator is a comma.
    (defun crm-indicator (args)
      (cons (format "[CRM%s] %s"
                    (replace-regexp-in-string
                     "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
                     crm-separator)
                    (car args))
            (cdr args)))
    (advice-add #'completing-read-multiple :filter-args #'crm-indicator)

    ;; Do not allow the cursor in the minibuffer prompt
    (setq minibuffer-prompt-properties
          '(read-only t cursor-intangible t face minibuffer-prompt))
    (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)

    ;; Emacs 28: Hide commands in M-x which do not work in the current mode.
    ;; Vertico commands are hidden in normal buffers.
    ;; (setq read-extended-command-predicate
    ;;       #'command-completion-default-include-p)

    ;; Enable recursive minibuffers
    (setq enable-recursive-minibuffers t))
#+end_src

** orderless

Load orderless for completion with space-seperated components
#+begin_src emacs-lisp
  (use-package orderless
    :init
    ;; Configure a custom style dispatcher (see the Consult wiki)
    ;; (setq orderless-style-dispatchers '(+orderless-dispatch)
    ;;       orderless-component-separator #'orderless-escapable-split-on-space)
    (setq completion-styles '(orderless basic)
          completion-category-defaults nil
          completion-category-overrides '((file (styles partial-completion)))))
#+end_src

** marginalia

Load marginalia for minibuffer annotations
#+begin_src emacs-lisp
  (use-package marginalia
    ;; Either bind `marginalia-cycle` globally or only in the minibuffer
    :bind (("M-A" . marginalia-cycle)
           :map minibuffer-local-map
           ("M-A" . marginalia-cycle))
    ;; The :init configuration is always executed (Not lazy!)
    :init
    ;; Must be in the :init section of use-package such that the mode gets
    ;; enabled right away. Note that this forces loading the package.
    (marginalia-mode))
#+end_src

** consult

Load consult for various useful commands
#+begin_src emacs-lisp
  ;; Example configuration for Consult
  (use-package consult
    ;; Replace bindings. Lazily loaded due by `use-package'.
    :bind (;; C-c bindings in `mode-specific-map'
           ("C-c M-x" . consult-mode-command)
           ("C-c h" . consult-history)
           ("C-c k" . consult-kmacro)
           ("C-c m" . consult-man)
           ("C-c i" . consult-info)
           ([remap Info-search] . consult-info)
           ;; C-x bindings in `ctl-x-map'
           ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
           ;; ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
           ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
           ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
           ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
           ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
           ;; Custom M-# bindings for fast register access
           ("M-#" . consult-register-load)
           ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
           ("C-M-#" . consult-register)
           ;; Other custom bindings
           ("M-y" . consult-yank-pop)                ;; orig. yank-pop
           ;; M-g bindings in `goto-map'
           ("M-g e" . consult-compile-error)
           ("M-g f" . consult-flycheck)              ;; Alternative: consult-flymake
           ;; ("M-g g" . consult-goto-line)             ;; orig. goto-line
           ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
           ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
           ("M-g m" . consult-mark)
           ("M-g k" . consult-global-mark)
           ("M-g i" . consult-imenu)
           ("M-g I" . consult-imenu-multi)
           ;; M-s bindings in `search-map'
           ("M-s d" . consult-find)
           ("M-s D" . consult-locate)
           ("M-s g" . consult-grep)
           ("M-s G" . consult-git-grep)
           ("M-s r" . consult-ripgrep)
           ("M-s l" . consult-line)
           ("M-s L" . consult-line-multi)
           ("M-s k" . consult-keep-lines)
           ("M-s u" . consult-focus-lines)
           ;; Isearch integration
           ("M-s e" . consult-isearch-history)
           :map isearch-mode-map
           ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
           ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
           ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
           ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
           ;; Minibuffer history
           :map minibuffer-local-map
           ("M-s" . consult-history)                 ;; orig. next-matching-history-element
           ("M-r" . consult-history))                ;; orig. previous-matching-history-element

    ;; Enable automatic preview at point in the *Completions* buffer. This is
    ;; relevant when you use the default completion UI.
    :hook (completion-list-mode . consult-preview-at-point-mode)

    ;; The :init configuration is always executed (Not lazy)
    :init

    ;; Optionally configure the register formatting. This improves the register
    ;; preview for `consult-register', `consult-register-load',
    ;; `consult-register-store' and the Emacs built-ins.
    (setq register-preview-delay 0.5
          register-preview-function #'consult-register-format)

    ;; Optionally tweak the register preview window.
    ;; This adds thin lines, sorting and hides the mode line of the window.
    (advice-add #'register-preview :override #'consult-register-window)

    ;; Use Consult to select xref locations with preview
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)

    ;; Configure other variables and modes in the :config section,
    ;; after lazily loading the package.
    :config

    ;; Optionally configure preview. The default value
    ;; is 'any, such that any key triggers the preview.
    ;; (setq consult-preview-key 'any)
    ;; (setq consult-preview-key "M-.")
    ;; (setq consult-preview-key '("S-<down>" "S-<up>"))
    ;; For some commands and buffer sources it is useful to configure the
    ;; :preview-key on a per-command basis using the `consult-customize' macro.
    (consult-customize
     consult-theme :preview-key '(:debounce 0.2 any)
     consult-ripgrep consult-git-grep consult-grep
     consult-bookmark consult-recent-file consult-xref
     consult--source-bookmark consult--source-file-register
     consult--source-recent-file consult--source-project-recent-file
     ;; :preview-key "M-."
     :preview-key '(:debounce 0.4 any))

    ;; Optionally configure the narrowing key.
    ;; Both < and C-+ work reasonably well.
    (setq consult-narrow-key "<") ;; "C-+"

    ;; Optionally make narrowing help available in the minibuffer.
    ;; You may want to use `embark-prefix-help-command' or which-key instead.
    ;; (define-key consult-narrow-map (vconcat consult-narrow-key "?") #'consult-narrow-help)

    ;; By default `consult-project-function' uses `project-root' from project.el.
    ;; Optionally configure a different project root function.
    ;;;; 1. project.el (the default)
    ;; (setq consult-project-function #'consult--default-project--function)
    ;;;; 2. vc.el (vc-root-dir)
    ;; (setq consult-project-function (lambda (_) (vc-root-dir)))
    ;;;; 3. locate-dominating-file
    ;; (setq consult-project-function (lambda (_) (locate-dominating-file "." ".git")))
    ;;;; 4. projectile.el (projectile-project-root)
    ;; (autoload 'projectile-project-root "projectile")
    ;; (setq consult-project-function (lambda (_) (projectile-project-root)))
    ;;;; 5. No project support
    ;; (setq consult-project-function nil)
  )
  (use-package consult-flycheck
    :after consult)
#+end_src

** xclip

Copy + paste from clipboard
#+begin_src emacs-lisp
  (use-package xclip)
  (xclip-mode 1)
#+end_src

** company (commented out)

# Load company to facilitate auto-complete.
# Auto-complete behaviour is configured in each mode individually.
# #+begin_src emacs-lisp
#   (use-package company
#     :ensure t
#     :custom
#     (company-idle-delay 0.0 "Recommended by lsp")
#     (company-ispell-available t)
#     (company-ispell-dictionary (expand-file-name "wordlist"
#                                                  dotemacs-extras-directory))
#     :config (global-company-mode '(LaTeX-mode latex-mode))) ;; enable company for latex only

#   ;; make company respect cases
#   (setq company-dabbrev-downcase nil)
# #+end_src

** corfu + cape

Load corfu for autocomplete
#+begin_src emacs-lisp
(use-package corfu
  ;; Optional customizations
  :custom
  (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
  (corfu-auto t)                 ;; Enable auto completion
  ;; (corfu-separator ?\s)          ;; Orderless field separator
  ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
  ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
  ;; (corfu-preview-current nil)    ;; Disable current candidate preview
  ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
  ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches
  ;; (corfu-scroll-margin 5)        ;; Use scroll margin

  ;; Enable Corfu only for certain modes.
  ;; :hook ((prog-mode . corfu-mode)
  ;;        (shell-mode . corfu-mode)
  ;;        (eshell-mode . corfu-mode))

  ;; Recommended: Enable Corfu globally.
  ;; This is recommended since Dabbrev can be used globally (M-/).
  ;; See also `corfu-exclude-modes'.
  :init
  (global-corfu-mode))

;; A few more useful configurations...
(use-package emacs
  :init
  ;; TAB cycle if there are only few candidates
  (setq completion-cycle-threshold 3)

  ;; Emacs 28: Hide commands in M-x which do not apply to the current mode.
  ;; Corfu commands are hidden, since they are not supposed to be used via M-x.
  ;; (setq read-extended-command-predicate
  ;;       #'command-completion-default-include-p)

  ;; Enable indentation+completion using the TAB key.
  ;; `completion-at-point' is often bound to M-TAB.
  ;; (setq tab-always-indent 'complete)
)
#+end_src

Load cape to use company backends for corfu
#+begin_src emacs-lisp
(use-package cape
  ;; Bind dedicated completion commands
  ;; Alternative prefix keys: C-c p, M-p, M-+, ...
  :bind (("C-c p p" . completion-at-point) ;; capf
         ("C-c p t" . complete-tag)        ;; etags
         ("C-c p d" . cape-dabbrev)        ;; or dabbrev-completion
         ("C-c p h" . cape-history)
         ("C-c p f" . cape-file)
         ("C-c p k" . cape-keyword)
         ("C-c p s" . cape-symbol)
         ("C-c p a" . cape-abbrev)
         ("C-c p l" . cape-line)
         ("C-c p w" . cape-dict)
         ("C-c p \\" . cape-tex)
         ("C-c p _" . cape-tex)
         ("C-c p ^" . cape-tex)
         ("C-c p &" . cape-sgml)
         ("C-c p r" . cape-rfc1345))
  :init
  ;; Add `completion-at-point-functions', used by `completion-at-point'.
  ;; NOTE: The order matters!
  (add-to-list 'completion-at-point-functions #'cape-dabbrev)
  (add-to-list 'completion-at-point-functions #'cape-file)
  ;; (add-to-list 'completion-at-point-functions #'cape-elisp-block)
  ;;(add-to-list 'completion-at-point-functions #'cape-history)
  ;;(add-to-list 'completion-at-point-functions #'cape-keyword)
  ;;(add-to-list 'completion-at-point-functions #'cape-tex)
  ;;(add-to-list 'completion-at-point-functions #'cape-sgml)
  ;;(add-to-list 'completion-at-point-functions #'cape-rfc1345)
  ;;(add-to-list 'completion-at-point-functions #'cape-abbrev)
  ;;(add-to-list 'completion-at-point-functions #'cape-dict)
  ;;(add-to-list 'completion-at-point-functions #'cape-symbol)
  ;;(add-to-list 'completion-at-point-functions #'cape-line)
)
#+end_src

** prescient

Load prescient for better ordering of completions
#+begin_src emacs-lisp
  (use-package prescient
    :after vertico)
  (use-package vertico-prescient
    :after vertico
    :init
    (vertico-prescient-mode))
#+end_src


* Org Mode

This section configures how org-mode behaves.

** load org mode with auto-indent

#+begin_src emacs-lisp
  (defun org-mode-setup ()
    (org-indent-mode)
    ;; (variable-pitch-mode 1)
    (visual-line-mode 1))
  (use-package org
    :hook (org-mode . org-mode-setup)
    :config
    (setq org-ellipsis " ▾"))
#+end_src

** auto-tangle this configuration file

Tangle this config file automatically after each save.
#+begin_src emacs-lisp
  (defun org-babel-tangle-emacs-config ()
    (when (string-equal (buffer-file-name) (expand-file-name "~/.emacs.d/init.org"))
      (let ((org-confirm-babel-evaluate nil)) (org-babel-tangle))))
  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'org-babel-tangle-emacs-config)))
#+end_src

** enable indentation in source block

Indent code in source block as they would be in source files.
#+begin_src emacs-lisp
  (setq org-src-tab-acts-natively t)
#+end_src

** allow shift select

Allow use of shift to select
#+begin_src emacs-lisp
  (setq org-support-shift-select t)
#+end_src


* Git
** magit

Load magit.
#+begin_src emacs-lisp
  (use-package magit
    :commands magit-status)
#+end_src


* Shell
** Bash and bash aliases

Use bash as default shell and use bash aliases
#+begin_src emacs-lisp
  (setq explicit-shell-file-name "/bin/bash")
  (setq shell-file-name "bash")
  (setq explicit-bash.exe-args '("--noediting" "--login" "-ic"))
  (setq shell-command-switch "-ic")
  (setenv "SHELL" shell-file-name)
#+end_src



* Latex
** auctex

Load auctex and reftex
#+begin_src emacs-lisp
  (use-package tex
    :ensure auctex
    :mode
    ("\\.tex\\'" . latex-mode)
  )
    ;; :mode "\\.tex\\'")
  (add-hook 'LaTeX-mode-hook #'reftex-mode)
  (add-hook 'latex-mode-hook #'reftex-mode)
#+end_src

Auto-parse tex file on load and save
#+begin_src emacs-lisp
  (setq TeX-parse-self t)
  (setq TeX-auto-save t)
#+end_src

Never assume current file is master file and always Query for master file
#+begin_src emacs-lisp
  (setq-default TeX-master nil)
#+end_src

Register lstlisting as verbatim environment, ignore it for syntax highlighting
#+begin_src emacs-lisp
  (eval-after-load 'latex '(add-to-list 'LaTeX-verbatim-environments "lstlisting"))
#+end_src

Highlight \cref like \ref
#+begin_src emacs-lisp
  (setq font-latex-match-reference-keywords
        '(
           ("cref" "{")
         )
  )
#+end_src

Enable spellcheck by default
#+begin_src emacs-lisp
  (add-hook 'LaTeX-mode-hook #'turn-on-flyspell)
#+end_src

** company-backends

# Load and group various company latex backends (company)
# #+begin_src emacs-lisp
#   (defun sb/company-latex-mode ()
#     "Add backends for latex completion in company mode."
#     (use-package math-symbol-lists ; Required by ac-math and company-math
#       :ensure t)
#     (use-package company-math
#       :ensure t)
#     (use-package company-reftex
#       :ensure t)
#     (use-package company-bibtex
#       :ensure t)
#     (use-package company-auctex
#       :ensure t)
#     (make-local-variable 'company-backends)
#     (setq-local company-backends
#                 (append '((:separate company-math-symbols-latex
#                                      company-math-symbols-unicode
#                                      company-latex-commands))
#                         company-backends))

#     (setq-local company-backends
#                 (append '((:separate company-reftex-labels
#                                      company-reftex-citations))
#                         company-backends))
#     (company-auctex-init))
#   (dolist (hook '(latex-mode-hook LaTeX-mode-hook))
#     (add-hook hook #'sb/company-latex-mode))
# #+end_src

Load various company latex backends via cape for corfu (for autocomplete)
#+begin_src emacs-lisp
  (use-package company-math
    :after tex
    :init
    (defun math-setup-capf ()
      (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-math-symbols-latex))
      (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-math-symbols-unicode))
      (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-latex-commands)))
    :hook
    (LaTeX-mode . math-setup-capf))

  (use-package company-reftex
    :after tex
    :init
    (defun reftex-setup-capf ()
      (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-reftex-labels))
      (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-reftex-citations)))
    :hook
    (LaTeX-mode . reftex-setup-capf))

  (use-package company-auctex
    :after tex
    :init
    (defun auctex-setup-capf ()
      (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-auctex-labels))
      (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-auctex-bibs))
      (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-auctex-macros))
      (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-auctex-symbols))
      (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-auctex-environments)))
    :hook
    (LaTeX-mode . auctex-setup-capf))
#+end_src

** pdf-tools
Use and sync with pdf-tools
#+begin_src emacs-lisp
  (use-package pdf-tools
    :after tex
    :config
    (pdf-tools-install))
  (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
        TeX-view-program-list '(("PDF Tools" TeX-pdf-tools-sync-view))
        TeX-source-correlate-mode t
        TeX-source-correlate-start-server t)
  (add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
#+end_src

** powerthesaurus

Load powerthesaurus for looking up synonyms, antonyms and related terms
#+begin_src emacs-lisp
  (use-package powerthesaurus
    :after tex)
#+end_src


* C++

** indentation

Disable tabsIndentation after open round brackets
#+begin_src emacs-lisp
  (setq-default c-default-style "linux"
                c-basic-offset 2)
#+end_src

** singular

Turn on C++-mode for files ending in ".sing" and ".lib" for Singular
#+begin_src emacs-lisp
  (setq auto-mode-alist (cons '("\\.sing\\'" . c++-mode) auto-mode-alist))
  (setq auto-mode-alist (cons '("\\.lib\\'" .  c++-mode) auto-mode-alist))
#+end_src



* Julia

Editing julia
#+begin_src emacs-lisp
  (use-package julia-mode
    :mode "\\.jl\\'")
#+end_src

Running julia
#+begin_src emacs-lisp
  (add-to-list 'load-path "/home/ren/julia-1.8.5/bin/julia")
  (use-package julia-repl
    :after julia-mode)
  (add-hook 'julia-mode-hook 'julia-repl-mode) ;; always use minor mode
#+end_src

Shift+space send current line or region to a terminal buffer
#+begin_src emacs-lisp
  (defun send-region-or-current-line-to-terminal ()
    "Send the region or the current line to the terminal buffer."
    (interactive)
    (let ((current-line (if (use-region-p)
                            (buffer-substring (region-beginning) (region-end))
                          (thing-at-point 'line t))))
      (with-current-buffer (get-buffer-create "*terminal*")
        (comint-send-string (get-buffer-process (current-buffer))
                            (concat current-line "\n"))))
    (forward-line 1))

  (defun my-julia-mode-hook ()
    (define-key julia-mode-map (kbd "S-SPC") 'send-region-or-current-line-to-terminal))

  (add-hook 'julia-mode-hook 'my-julia-mode-hook)
#+end_src
